### General project setup
general:
  gitHttpsCredentialsId: 'c2258d29-8af2-40ed-85ef-13a5d4b17308'
  buildTool: 'mta'
  productiveBranch: 'master'
  verbose: true

### Step-specific configuration
steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    cloudFoundry:
      org: 'ic-adv-dev'
      space: 'Dev - CI/CD Trainer'
      credentialsId: 'trainer-cf'
  artifactPrepareVersion:
    buildTool: mta
    includeCommitId: false
    versioningType: cloud
  executeBuild:
    xMakeJobName: 'I534404-innovator-challenge-2021-demoapp-SP-MS-common'
    nextGenXMake: true
    xMakeNovaCredentialsId: 'I534404-xMakeNova' 
    buildTool: mta

### Stage-specific configuration
stages:
  #'Init':
    #artifactPrepareVersion: false
  'Central Build':
    buildExecute : true
  'Confirm':
    manualConfirmation: false
  'Release':
    cloudFoundryDeploy: true
