### General project setup
general:
  gitHttpsCredentialsId: 'trainer-git'
  buildTool: 'mta'
  productiveBranch: 'master'
  verbose: true

### Step-specific configuration
steps:
  cloudFoundryDeploy:
    cloudFoundry:
      org: 'ic-adv-dev'
      space: 'Dev - CI/CD Trainer'
      credentialsId: 'trainer-cf'
  artifactPrepareVersion:
    buildTool: mta
    includeCommitId: false
    versioningType: cloud

### Stage-specific configuration
stages:
  #'Init':
    #artifactPrepareVersion: false
  'Central Build':
    buildExecute : true
  'Confirm':
    manualConfirmation: false
  'Release':
    cloudFoundryDeploy: true