### General project setup
general:
  gitSshKeyCredentialsId: 'trainer-git'
  buildTool: 'mta'
  productiveBranch: 'master'
  verbose: true
  
### Step-specific configuration
steps:
  cloudFoundryDeploy:
    cloudFoundry:
      org: 'ic-adv-dev'
      space: 'Dev - CI/CD Trainer'
      credentialsId: 'trainer-cf'

### Stage-specific configuration
stages:
  'Init':
    artifactPrepareVersion: false
  'Central Build':
    buildExecute : true
  'Confirm':
    manualConfirmation: false
  'Release':
    cloudFoundryDeploy: true